name: ipc-chip-tests

on:
  push:
    branches:
      - master

jobs:
  zftlabs-tests:
    needs: build-musl-static
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup env variables
        run: |
          echo "::set-env name=GIT_HASH::$(git rev-parse --short $GITHUB_SHA)"

      - name: Executing tests
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ZFTLABS_HOST }}
          username: ${{ secrets.ZFTLABS_USER }}
          port: ${{ secrets.ZFTLABS_PORT }}
          key: ${{ secrets.ZFTLABS_KEY }}
          envs: GITHUB_SHA
          script: whoami
