name: ipc-chip-tests

on:
  repository_dispatch:
    types: [ci-tests]

jobs:
  ci-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        lab-name:
          - zftlab
          - dlab

      fail-fast: false

    steps:
      - name: Executing tests
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CI_HOST }}
          username: ${{ secrets.CI_USER }}
          port: ${{ secrets.CI_PORT }}
          key: ${{ secrets.CI_KEY }}
          script: |
            SHA=${{ github.event.client_payload.sha }} py.test -v -s --color=yes \
              ipc_chip_info_tests/ipc_chip_test.py::test_${{ matrix.lab-name }}
