name: ipc-chip-info

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  musl-static:
    runs-on: ubuntu-latest

    steps:
      - uses: pozetroninc/github-action-get-latest-release@master
        id: ct-ng-release
        with:
          owner: widgetii
          repo: ct-ng-builds

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: |
          REL="${{ steps.ct-ng-release.outputs.release }}"
          echo "Got release $REL"
          wget -qO- https://github.com/widgetii/ct-ng-builds/releases/download/$REL/arm-unknown-linux-gnueabi.tar.xz | \
            tar xfJ - -C /opt
          ls -la /opt
