name: ipc-chip-info

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  musl-static:
    runs-on: ubuntu-latest

    env:
      TOOLCHAIN: arm-unknown-linux-musleabi

    steps:
      - uses: pozetroninc/github-action-get-latest-release@master
        id: ct-ng-release
        with:
          owner: widgetii
          repo: ct-ng-builds

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build sources
        run: |
          REL="${{ steps.ct-ng-release.outputs.release }}"
          echo "Got release $REL"
          wget -qO- https://github.com/widgetii/ct-ng-builds/releases/download/$REL/$TOOLCHAIN.tar.xz | \
            tar xfJ - -C /opt
          export PATH=/opt/$TOOLCHAIN/bin:$PATH
          sudo apt install -y cmake
          cmake -H. -Bbuild -DCMAKE_C_COMPILER=${TOOLCHAIN}-gcc -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: "Development Build"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          files: "build/ipc_chip_info"
